// Generated by https://quicktype.io

export interface Sistema {
    racas:           Raca[];
    caminhos:        Caminho[];
    cidades:         Cidade[];
    descendencias:   Descendencia[];
    habilidades:     Habilidade[];
    habitos:         Habito[];
    idiomas:         Idioma[];
    patronos:        Patrono[];
    especializacoes: Especializacoe[];
}

export interface Caminho {
    idCaminho:       number;
    nomeCaminho:     string;
    descCaminho:     string;
    habilidades:     Habilidade[];
    especializacoes: any[];
    habitos:         Habito[];
}

export interface Habilidade {
    idHabilidade:   number;
    nomeHabilidade: string;
    atrAtacante:    string;
    tipoHabilidade: string;
    utiHabilidade:  string;
    descHabilidade: string;
    prerequisito:   string;
    nivelRequerido: number;
    acoes:          Acoe[];
    gasto:          any[];
    situacoes:      Situacoe[];
}

export interface Acoe {
    idAcao:   number;
    nomeacao: string;
}

export interface Situacoe {
    idSituacao:   number;
    nomeSituacao: string;
    descSituacao: string;
}

export interface Habito {
    idHabito:        number;
    nomeHabito:      string;
    descHabito:      string;
    qtdFichaHabito:  null;
    especializacoes: Especializacoe[];
}

export interface Especializacoe {
    idEspecializacao:   number;
    nomeEspecializacao: string;
    descEspecializacao: string;
}

export interface Cidade {
    idCidade:   number;
    nomeCidade: string;
    descCidade: string;
    popCidade:  string;
}

export interface Descendencia {
    idDescendencia:   number;
    nomeDescendencia: string;
    descDescendencia: string;
    habilidades:      Habilidade[];
    habitos:          Habito[];
    sanidade:         null;
    situacoes:        any[];
}

export interface Idioma {
    idIdioma:   number;
    nomeIdioma: string;
    descIdioma: string;
}

export interface Patrono {
    idPatrono:   number;
    nomePatrono: string;
    descPatrono: string;
}

export interface Raca {
    idRaca:             number;
    nomeRaca:           string;
    raridadeRaca:       string;
    descRaca:           string;
    longevidadeRaca:    string;
    culturaRaca:        string;
    historiaRaca:       string;
    racaForca:          number;
    racaConstituicao:   number;
    racaAgilidade:      number;
    racaDestreza:       number;
    racaInteligencia:   number;
    racaSabedoria:      number;
    racaCarisma:        number;
    sangue:             number;
    vigor:              number;
    descendencias:      Descendencia[];
    especializacoes:    Especializacoe[];
    habilidades:        Habilidade[];
    habitos:            Habito[];
    idiomas:            any[];
    patronos:           Patrono[];
    tracosfisiologicos: string;
}
